### PR TITLE
Update architect_schedulegroups.md

### PR DESCRIPTION
**Pull request by abejaranoh**
"data." is not required on genesyscloud_architect_schedulegroups/open_schedules_id and generates an error

### CODE REVIEW

**Review by charliecon — CHANGES_REQUESTED** [review]
This change should be made inside `examples/resources/genesyscloud_architect_schedulegroups/resource.tf` 

Then run the command `make docs` from the root of the project to update the contents inside /docs

**Comment by abejaranoh** [comment]
changed as requested

**Review by charliecon — APPROVED** [review]

**Comment by charliecon** [comment]
Would you mind setting the target branch of the PR as `dev` instead of `main`? We will be merging to dev next week for release. Sorry I didn't catch this earlier

**Comment by charliecon** [comment]
There were some merge conflicts introduced after changing the target branch to dev. No need to fix them - I opened a separate PR to make this change. Thanks for highlighting this!

**Pull request closed without merging**
