### PR TITLE
[JM-1466]: Upgrade the platform client version

### PR DESCRIPTION
**Pull request by Rafat001**
Change the platform client version from v130 to v131

### CODE REVIEW

**Comment by dginty4** [comment]
Is this so you can get access to a new api?

**Comment by Rafat001** [comment]
> Is this so you can get access to a new api?

Not a new api, There was a small contract change. I need that to implement exporter and data source. Currently our resource doesn't have these

**Review by dginty4 — APPROVED** [review]

**Review by charliecon — APPROVED** [review]

**Comment by dginty4** [comment]
@Rafat001 Just a few conflicts to resolve the we can merge

**Comment by carnellj-genesys** [comment]
@Rafat001 Can you please resolved merge dependencies and then we can merge

**Pull request merged**
