### PR TITLE
FEAT/vip-routing-queue-settings Add direct routing object to queue

### PR DESCRIPTION
**Pull request by jonesb-genesys**
This request adds Direct Routing information to the Queue object so that a Direct Routing Queue can be created within the genesys terraform provider

### CODE REVIEW

**Comment by jonesb-genesys** [comment]
Also vip was updated in naming to Direct Routing so do not mind the branch naming which was made before that switch

**Comment by jonesb-genesys** [comment]
Not entirely sure what that failure means for the PR labeler

**Comment by charliecon** [comment]
Hi @jonesb-genesys 

Sorry about the delay. 

You need to run `go generate` to update the contents in `/docs`. Also I noticed some very minor formatting mistakes, running `go fmt path/to/edited/file` should fix those up.

Finally, I'm going to create a branch in our repo (also called `feat/vip-routing-queue-settings`), could you please edit the PR to merge into that branch? It will allow us to run our pipeline tests against the changes to be sure everything looks okay before merging into main.

Thanks

**Comment by jonesb-genesys** [comment]
No problem I will get those things done and updated, thanks!

**Comment by jonesb-genesys** [comment]
Looks like after the generate a lot of files got terraform-provider-genesyscloud-jonesb added instead of terraform-provider-genesyscloud. Is there something I should do to avoid that when using `go generate`?

**Comment by charliecon** [comment]
> Looks like after the generate a lot of files got terraform-provider-genesyscloud-jonesb added instead of terraform-provider-genesyscloud. Is there something I should do to avoid that when using `go generate`?

That's strange, I've never seen that before. I'll take a look into it

**Comment by charliecon** [comment]
@jonesb-genesys I cloned your repo and tried to recreate the issue but I was unable to. Just to confirm, you're running `go generate` at the root of the project?

**Comment by jonesb-genesys** [comment]
Yeah, but my root is named, terraform-provider-genesyscloud-jonesb, if that would do it?

**Comment by charliecon** [comment]
Yeah, not sure how exactly but that must be it

**Comment by jonesb-genesys** [comment]
I will re run and get it updated back to the correct files

**Comment by jonesb-genesys** [comment]
Ok got it fixed

**Review by charliecon — APPROVED** [review]

**Comment by charliecon** [comment]
Hey @jonesb-genesys 

If you follow this link, you'll see the error we're receiving when running your tests against our pipeline test org - [https://github.com/MyPureCloud/terraform-provider-genesyscloud/actions/runs/4251405819/jobs/7393751904#step:6:340](https://github.com/MyPureCloud/terraform-provider-genesyscloud/actions/runs/4251405819/jobs/7393751904#step:6:340)

I tested a fix myself by appending queue 1 name with a unique ID, but then the issue was that no details about direct_routing were coming back from the API. Are there any products or feature toggles I might need to enable?

Thanks

**Comment by jonesb-genesys** [comment]
Yeah there is a feature toggle `vip-experience.pure-3846`

**Pull request merged**
